export default function Engineering() {
  return <section className="section wrap" id="engineering" aria-labelledby="engineering-title">
    <div className="section-heading" data-reveal>
      <div><p className="eyebrow">Beyond materials research</p><h2 id="engineering-title">Applied AI and engineering projects</h2></div>
      <a className="text-link" href="https://github.com/hitheshrai" target="_blank" rel="noreferrer">More on GitHub <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a>
    </div>

    <div className="engineering-grid" data-reveal="scale">
      <figure className="engineering-photo"><img src="/assets/edge-llamacon.jpeg" width="675" height="380" alt="Four ASU Next Lab team members presenting EDge AI at LlamaCon 2025." loading="lazy"/><figcaption>ASU Next Lab presenting EDge AI at LlamaCon 2025 · Photo: ASU SolarSPELL</figcaption></figure>
      <div className="engineering-story"><p className="eyebrow">Featured · Next Lab + SolarSPELL</p><h3>EDge AI: testing an assistant that works offline</h3><p>With the team, compared latency, power, memory, and output quality on Jetson hardware, then helped prepare prototypes and demonstrations for partners. Led the team presentation at ASU’s 2025 Agentic AI conference; the project also appeared at FOLC Fest and Meta’s inaugural LlamaCon.</p><div className="engineering-links"><a className="text-link" href="https://nextlab.asu.edu/edge-ai/" target="_blank" rel="noreferrer">Project overview <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a><a className="text-link" href="https://nextlab.asu.edu/agentic-ai-and-the-student-experience/" target="_blank" rel="noreferrer">ASU presentation recap <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a><a className="text-link" href="https://solarspell.org/asu-solarspell-next-lab-pioneer-offline-ai" target="_blank" rel="noreferrer">SolarSPELL report <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a></div></div>
    </div>

    <div className="project-groups" data-reveal>
      <article><p className="eyebrow">Prototype testing at Next Lab</p><h3>Working within real constraints</h3><ul><li><strong>Technical trade-offs</strong><span>Compared latency, power, memory, and output quality for offline models on Jetson hardware.</span></li><li><strong>Team demonstrations</strong><span>Prepared technical work for partner feedback, FOLC Fest, LlamaCon, and ASU’s Agentic AI conference.</span></li><li><strong>Other prototypes</strong><span>Helped develop offline learning, research-briefing, and voice-interaction tools.</span></li></ul></article>
      <article><p className="eyebrow">Energy modeling and student leadership</p><h3>Additional work</h3><ul><li><strong>Grid storage</strong><span>Modeled battery storage and renewable generation with PyPSA.</span></li><li><strong>AEE at ASU</strong><span>Serve as president of ASU’s Association of Energy Engineers student chapter.</span></li><li><strong>EPICS · 2Unify Education</strong><span>Led a student team from 2022–2024 building Python and robotics activities for learners in the US and South Africa with Bridge2Africa.</span></li></ul></article>
      <article><p className="eyebrow">Project coverage and research records</p><h3>External accounts of shared work</h3><ul className="press-links"><li><a href="https://solarspell.org/asu-solarspell-next-lab-pioneer-offline-ai" target="_blank" rel="noreferrer"><strong>ASU SolarSPELL & Next Lab pioneer offline AI</strong><span>Feature · SolarSPELL ↗</span></a></li><li><a href="https://annualreport.swissnex.org/projects/project-doing-research-in-switzerland-campaign-launch/" target="_blank" rel="noreferrer"><strong>Doing Research in Switzerland</strong><span>Video · Swissnex ↗</span></a></li><li><a href="https://letiandougroup.com/2023/05/25/surf-students/" target="_blank" rel="noreferrer"><strong>Purdue summer research</strong><span>Lab post · Letian Dou Group ↗</span></a></li><li><a href="https://forge.engineering.asu.edu/participant/rai-purushothama-hithesh/" target="_blank" rel="noreferrer"><strong>Three perovskite research projects</strong><span>Research records · ASU Forge ↗</span></a></li></ul></article>
    </div>

    <p className="rail-hint" aria-hidden="true">Swipe through project photographs →</p>
    <div className="work-photo-rail" role="region" aria-label="Selected projects and leadership photographs" tabIndex={0} data-reveal>
      <figure className="photo-card" tabIndex={0}><img src="/assets/nextlab-showcase.jpg" width="768" height="1024" alt="Hithesh presenting a low-latency music collaboration project with Zoom at the ASU Enterprise Technology Town Hall." loading="lazy"/><figcaption><strong>ASU Enterprise Technology Town Hall</strong><span>Next Lab · Studio Associate</span><span>Low-latency music collaboration with Zoom</span></figcaption></figure>
      <figure className="photo-card" tabIndex={0}><img src="/assets/aee-chapter.jpg" width="800" height="600" alt="Members of the Association of Energy Engineers student chapter at ASU." loading="lazy"/><figcaption><strong>AEE at ASU · 2026</strong><span>Student Chapter President</span><span>Energy, storage, manufacturing, and compute</span></figcaption></figure>
      <figure className="photo-card" tabIndex={0}><img src="/assets/nextlab-team.jpg" width="1525" height="1016" alt="The ASU Next Lab team gathered in the lab in Tempe." loading="lazy"/><figcaption><strong>ASU Next Lab · Tempe</strong><span>Studio Associate · Management Intern</span><span>Applied AI, edge systems, and student-led prototypes</span></figcaption></figure>
      <figure className="photo-card" tabIndex={0}><img src="/assets/first-solar-visit.jpg" width="800" height="600" alt="Students in safety gear during a visit to First Solar's photovoltaic reliability site." loading="lazy"/><figcaption><strong>First Solar · Arizona</strong><span>Photovoltaic reliability site visit</span><span>Manufacturing, testing, and field reliability</span></figcaption></figure>
    </div>
  </section>;
}
