export default function Engineering() {
  return <section className="section wrap" id="engineering" aria-labelledby="engineering-title">
    <div className="section-heading" data-reveal>
      <div><p className="eyebrow">04 / Projects & leadership</p><h2 id="engineering-title">Helping technical teams move.</h2></div>
      <a className="text-link" href="https://github.com/hitheshrai" target="_blank" rel="noreferrer">More on GitHub <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a>
    </div>

    <div className="engineering-grid" data-reveal="scale">
      <figure className="engineering-photo"><img src="/assets/edge-llamacon.jpeg" width="675" height="380" alt="Four ASU Next Lab team members presenting EDge AI at LlamaCon 2025." loading="lazy"/><figcaption>ASU Next Lab presenting EDge AI at LlamaCon 2025 · Photo: ASU SolarSPELL</figcaption></figure>
      <div className="engineering-story"><p className="eyebrow">Featured · EDge AI</p><h3>From a partner goal to a working demonstration.</h3><p>Worked across Next Lab and SolarSPELL to turn offline community AI into hardware tests, model trade-offs, demonstrations, and shared technical decisions. Kept power, memory, connectivity, and output quality visible throughout. Led the team presentation at ASU’s 2025 Agentic AI conference; the work also appeared at FOLC Fest and Meta’s inaugural LlamaCon.</p><div className="engineering-links"><a className="text-link" href="https://nextlab.asu.edu/edge-ai/" target="_blank" rel="noreferrer">Next Lab project <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a><a className="text-link" href="https://nextlab.asu.edu/agentic-ai-and-the-student-experience/" target="_blank" rel="noreferrer">Conference recap <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a><a className="text-link" href="https://solarspell.org/asu-solarspell-next-lab-pioneer-offline-ai" target="_blank" rel="noreferrer">SolarSPELL feature <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a></div></div>
    </div>

    <div className="project-groups" data-reveal>
      <article><p className="eyebrow">Program work at Next Lab</p><h3>Connect the people, constraints, and build.</h3><ul><li><strong>Technical trade-offs</strong><span>Compared latency, power, memory, and output quality for offline models on Jetson hardware.</span></li><li><strong>Team delivery</strong><span>Led the EDge AI presentation at ASU’s Agentic AI conference and supported team demonstrations at FOLC Fest and LlamaCon.</span></li><li><strong>Working prototypes</strong><span>Helped move offline learning, research-briefing, and voice-assistant ideas into systems that teams could test.</span></li></ul></article>
      <article><p className="eyebrow">Energy at scale</p><h3>From devices to infrastructure.</h3><ul><li><strong>Grid storage</strong><span>Modeled battery storage and renewable integration with PyPSA.</span></li><li><strong>AEE at ASU</strong><span>President, connecting energy, storage, manufacturing, and compute.</span></li><li><strong>EPICS · 2Unify Education</strong><span>Team lead, 2022–2024: led 10–15 students building Python and robotics activities for learners in the US and South Africa with Bridge2Africa.</span></li></ul></article>
      <article><p className="eyebrow">Writing & public work</p><h3>Selected stories and records.</h3><ul className="press-links"><li><a href="https://solarspell.org/asu-solarspell-next-lab-pioneer-offline-ai" target="_blank" rel="noreferrer"><strong>ASU SolarSPELL & Next Lab pioneer offline AI</strong><span>Feature · SolarSPELL ↗</span></a></li><li><a href="https://annualreport.swissnex.org/projects/project-doing-research-in-switzerland-campaign-launch/" target="_blank" rel="noreferrer"><strong>Doing Research in Switzerland</strong><span>Video · Swissnex ↗</span></a></li><li><a href="https://letiandougroup.com/2023/05/25/surf-students/" target="_blank" rel="noreferrer"><strong>SURF students</strong><span>Lab post · Letian Dou Group ↗</span></a></li><li><a href="https://forge.engineering.asu.edu/furiproject/measuring-and-controlling-mobile-ion-concentration-to-improve-operational-stability-in-perovskite-thin-films/" target="_blank" rel="noreferrer"><strong>Measuring and Controlling Mobile Ion Concentration</strong><span>Research record · ASU FURI ↗</span></a></li></ul></article>
    </div>

    <p className="rail-hint" aria-hidden="true">Swipe through project photographs →</p>
    <div className="work-photo-rail" role="region" aria-label="Selected projects and leadership photographs" tabIndex={0} data-reveal>
      <figure><img src="/assets/nextlab-showcase.jpg" width="768" height="1024" alt="Hithesh presenting a low-latency music collaboration project with Zoom at the ASU Enterprise Technology Town Hall." loading="lazy"/><figcaption>Low-latency music collaboration with Zoom · Enterprise Technology Town Hall</figcaption></figure>
      <figure><img src="/assets/aee-chapter.jpg" width="800" height="600" alt="Members of the Association of Energy Engineers student chapter at ASU." loading="lazy"/><figcaption>AEE at ASU</figcaption></figure>
      <figure><img src="/assets/first-solar-visit.jpg" width="800" height="600" alt="Students in safety gear during a visit to First Solar's photovoltaic reliability site." loading="lazy"/><figcaption>First Solar reliability site visit</figcaption></figure>
    </div>
  </section>;
}
